const Asteroid_Details_Action_Types = {
  ASTEROID_DETAILS: 'ASTEROID_DETAILS',
  ASTEROID_DETAILS_SUCCESS: 'ASTEROID_DETAILS_SUCCESS',
  ASTEROID_DETAILS_FAILURE: 'ASTEROID_DETAILS_FAILURE',
};

export default Asteroid_Details_Action_Types;
