const Random_Asteroid_Action_Types = {
  GET_RANDOM_ASTEROID: 'GET_RANDOM_ASTEROID',
  GET_RANDOM_ASTEROID_SUCCESS: 'GET_RANDOM_ASTEROID_SUCCESS',
  GET_RANDOM_ASTEROID_FAILURE: 'GET_RANDOM_ASTEROID_FAILURE',
};

export default Random_Asteroid_Action_Types;
